In [3]:
m1 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
m2 = [[5, 2, 8], [3, 1, 2], [7, 0, 2]]

**Exercício 1: Soma de Matrizes**

Escreva  um  programa  em  Python  que  soma  duas  matrizes  de mesmo  tamanho.  As matrizes devem ser lidas como listas de listas e o resultado deve ser exibido na tela. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [236]:
import numpy as np

def sum_matrix(a, b):
    # verify is tha matrix had the same size
    a_len = len(a)
    b_len = len(b)
    
    print(a_len, b_len)
    if a_len != b_len:
        raise ValueError('matrix should had the same size')

    a_child_len = [len(a[i]) for i in range(a_len)]
    b_child_len = [len(b[i]) for i in range(b_len)]
    k = [i for i in range(len(a_child_len)) if a_child_len[i] != b_child_len[i]]

    if len(k):
        raise ValueError('matrix should had the same size')

    res = []
    for i in range(a_len):
        row = []
        for j in range(len(a[i])):
            row.append(a[i][j] + b[i][j])

        res.append(row)

    return res


sum_matrix(m1, m2), np.matrix(m1) + np.matrix(m2)

3 3


([[6, 4, 11], [3, 2, 6], [12, 6, 2]],
 matrix([[ 6,  4, 11],
         [ 3,  2,  6],
         [12,  6,  2]]))

**Exercício 2: Multiplicação de Matrizes**

Implemente  uma  função  em  Python  que  multiplica  duas  matrizes.  Verifique  se  as dimensões  das  matrizes  são  compatíveis  para  a  multiplicação  e  retorne  a  matriz  resultante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática

In [ ]:
import numpy as np

def multi_matrix(a, b):
    # verify is tha matrix had the same size
    a_rows = len(a)
    b_rows = len(b)

    a_cols = set([len(a[i]) for i in range(a_rows)])
    b_cols = set([len(b[i]) for i in range(b_rows)])
    

    if len(a_cols) > 1 or len(b_cols) > 1:
        raise ValueError("cols should be the same length")

    a_cols = list(a_cols)[0]
    b_cols = list(b_cols)[0]

    # (ar,ac) x (br,bc) -> ac == br
    if a_cols != b_rows:
        raise ValueError("unable to calculate the matriz multi")

    # result
    # (an,am) x (bn,bm) -> an,bm
    total = []

    for i in range(a_rows):
        r = []
        k = 0
        while k < b_cols:
            s = 0
            for j in range(a_cols):
                s += (a[i][j] * b[j][k])
            
            k += 1
            r.append(s)

        total.append(r)

    return total


print(multi_matrix(m1, m2))
print(np.matmul(m1, m2))

(3, 3) (3, 3)
[[32, 4, 18], [31, 1, 10], [43, 16, 52]]
[[32  4 18]
 [31  1 10]
 [43 16 52]]


**Exercício 3: Transposição de Matriz**

Crie um programa que calcula a transposta de uma matriz. A matriz deve ser inserida pelo usuário e o programa deve exibir a matriz transposta. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [ ]:
import numpy as np

def transpose(a):
    rows = len(a)
    cols = list(set([len(x) for x in a]))

    if len(cols) > 1:
        raise ValueError("invalid cols")

    cols = cols[0]
    shape = (rows, cols)
    
    T = []
    for i in range(cols): # new lines
        n_row = []
        for j in range(rows): # new columns
            n_row.append(a[j][i])

        T.append(n_row)

    return T


print(transpose(m1))
print(np.transpose(m1))

[[1, 0, 5], [2, 1, 6], [3, 4, 0]]
[[1 0 5]
 [2 1 6]
 [3 4 0]]


**Exercício 4: Traço de uma Matriz**

Desenvolva um script em Python que calcula o traço de uma matriz (soma dos elementos da  diagonal  principal).  O  programa  deve  funcionar  para  matrizes  quadradas  de  qualquer tamanho.  Apresente  a  solução  com  e  sem  o  uso  do  NumPy.  Pratique  suas  habilidades  de programação ao mesmo tempo que estuda Matemática.

In [ ]:
def matrix_trace(a):
    rows = len(a)
    cols = list(set([len(x) for x in a]))

    if len(cols) > 1:
        raise ValueError("invalid cols")

    cols = cols[0]
    shape = (rows, cols)

    if rows != cols:
        raise ValueError("invalid matrix format")

    # prev = 0
    total = 0
    for i in range(rows):
        total += a[i][i]
        # for j in range(cols):
        #     if prev == j:
        #         total += a[i][j]
        #         prev += 1
        #         break
        

    return total


matrix_trace(m1), np.matrix.trace(np.array(m1))

(2, np.int64(2))

**Exercício 5: Determinante de uma Matriz(Desafio)**

Escreva  uma  função  que  calcula  o  determinante  de  uma  matriz  quadrada.  Utilize  a recursividade ou o método de Laplace para calcular o determinante. Apresente a solução com e sem o uso do NumPy. Pratique suas habilidades de programação ao mesmo tempo que estuda Matemática.

In [5]:
import numpy as np

def select_row(m, r, c, rows, cols):
    selected_col = []
    for i in range(rows):
        r_a = []
        for j in range(cols):
            if i != r and j != c:
                r_a.append(m[i][j])
        
        if len(r_a):
            selected_col.append(r_a)
    
    return selected_col

def calc_deter(a):
    rows = len(a)
    cols = list(set([len(x) for x in a]))

    if len(cols) > 1:
        raise ValueError("invalid cols")

    cols = cols[0]
    shape = (rows, cols)
    if rows != cols:
        raise ValueError("invalid matrix format")

    if shape[0] == 2 and shape[1] == 2:
        return (a[0][0] * a[1][1]) - (a[0][1] * a[1][0])

    s_r = 0
    res = []
    for i in range(len(a[s_r])):
        se_r = select_row(a, s_r, i, rows, cols)
        if se_r:
            det = calc_deter(se_r)
            if s_r % 2 == 0:
                n = (a[s_r][i]) if i % 2 == 0 else -a[s_r][i]
            else:
                n = -(a[s_r][i]) if i % 2 == 0 else a[s_r][i]
            if det:
                # print(f"{n} (-1)^{s_r+1}+{i+1} * D{s_r+1}+{i+1}")
                # print(f"{n} {det}")
                res.append(n*det)
        # ss = ''
        # for p_r in range(len(se_r)):
        #     formatted = str(se_r[p_r]).replace('[', '|').replace(']', '|').replace(',', '')
        #     print(formatted)
        
    return sum(res)


a = [[12, 4, 19], [0,0,1], [37,2,5]]
b = [[29, 12, 89], [35, 182, 1271], [12, 92, 1211]]
c = [[1, 2], [3, 4]]
d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
# a = [[5, 6], [8, 9]]
print(calc_deter(m1))
print(np.linalg.det(m1))

1
0.9999999999999987
