### Machine Learning Apenas com Operações Matemáticas (Sem frameworks)

Vamos criar um modelo capas de prever o preço de um ativo financeiro com base na taxa nominal de juros

In [54]:
import numpy as np

# Gerando dados sintéticos
np.random.seed(0)

rng = np.random.default_rng(0)

X = rng.integers(1, 10, size = (100, 1)) # 100 instâncias, valores entre 1 e 10
y = 50000 + 30000 * X + rng.standard_normal(size=(100, 1)) * 15000 # Relação linear: preço base + preço ativo + ruído

In [55]:
X[1:5]

array([[6],
       [5],
       [3],
       [3]])

In [56]:
y[1:5]

array([[211875.22051577],
       [199933.1880032 ],
       [149847.12402615],
       [120674.57804376]])

In [57]:
# Adicionar coluna de uns para o termo de interceptação
X_b = np.c_[np.ones((100, 1)), X] # Adiciona x0 = 1 a cada instância

In [58]:
X_b

array([[1., 8.],
       [1., 6.],
       [1., 5.],
       [1., 3.],
       [1., 3.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [1., 8.],
       [1., 6.],
       [1., 9.],
       [1., 5.],
       [1., 6.],
       [1., 9.],
       [1., 7.],
       [1., 6.],
       [1., 5.],
       [1., 6.],
       [1., 9.],
       [1., 3.],
       [1., 8.],
       [1., 7.],
       [1., 1.],
       [1., 4.],
       [1., 8.],
       [1., 5.],
       [1., 1.],
       [1., 7.],
       [1., 7.],
       [1., 8.],
       [1., 2.],
       [1., 1.],
       [1., 8.],
       [1., 1.],
       [1., 5.],
       [1., 1.],
       [1., 3.],
       [1., 5.],
       [1., 4.],
       [1., 4.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [1., 7.],
       [1., 5.],
       [1., 6.],
       [1., 3.],
       [1., 6.],
       [1., 7.],
       [1., 4.],
       [1., 5.],
       [1., 9.],
       [1., 8.],
       [1., 9.],
       [1., 4.],
       [1., 7.],
       [1., 9.

### Função de Custo MSE com Operações Entre valores

Esta função dsa_func_custo é uma implementação da função de custo de erro quadrático médio, que é amplamente usada em regressão linear. O objetivo dessa função é medir quão bem o modelo de regressão (representado pelos parâmetros theta) está desempenhando em relação ao conjunto de dados (X e y). Um custo mas baixo indica que o modelo está fazendo previsões mais precisas.

In [59]:
def dsa_func_custo(X, y, theta):
    # m é o número de exemplos de treinamento (observações) no conjunto de dados
    m = len(y)

    # Calcula a função de custo para a regressão linear
    # A função de custo é a média dos erros quadrados entre as previsões e os valores reais
    # (1 / (2 * m)) é um fator de escala comum na função de custo do erro quadrático médio
    # np.sum(np.square(X.dot(theta) - y)) é a soma dos quadrados dos erros
    # X.dot(theta) é o produto escalar de X (dados de entradas) e theta (parâmetros do modelo)
    # X.dot(theta) - y é a diferença entre as previsões e os valores reais
    cost = (1/(2*m)) * np.sum(np.square(X.dot(theta) - y))

    return cost

### Algoritmo Gradiente Descendente com Operações Entre Valores

In [60]:
def dsa_gradient_descent(X, y, theta, learning_rate, iterations):
    # m é o número de exemplos de treinamento no conjuto de dados
    m = len(y)

    # Inicializa um array para armazenar o histórico de custo em cada iteração
    cost_history = np.zeros(iterations)

    # Loop para realizar o número especificado de iterações
    for i in range(iterations):
        # Calcula o gradiente da função de custo em relação a theta
        # O gradiente é a média dos produtos dos erros e as características de entrada
        gradients = 1/m * X.T.dot(X.dot(theta) - y)

        # Atualiza os parâmetros theta subtraindo o produto da taxa de aprendizado e o gradiente
        # Esta é a etapa de descida do gradiente, movendo-se em direção ao mínimo da função de custo
        theta = theta - learning_rate * gradients

        # calcula o custo com o theta atualizado e armazena no histórico de custo
        cost_history[i] = dsa_func_custo(X, y, theta)

    return theta, cost_history

### Treinamento do Modelo

In [61]:
# Parâmetros iniciais

# Iniciar os parâmetros randomicamente
theta = rng.standard_normal(size=(2, 1))

# Taxa de aprendizado
learning_rate = 0.01

# Número de passadas de treino
iterations = 1000

In [62]:
# Treinando o modelo
theta_final, cost_history = dsa_gradient_descent(X_b, y, theta, learning_rate, iterations)

In [63]:
print("Modelo de Machine Learning = Parâmetros Finais:\n", theta_final)

Modelo de Machine Learning = Parâmetros Finais:
 [[45739.57596361]
 [30665.86341129]]


### Deploy e Previsão com novos dados

In [64]:
X_new = np.array([[4.5]])

In [65]:
# Novo valor do bias
X_new_b = np.c_[np.ones((1, 1)), X_new]

In [66]:
# Previsão
y_predict = X_new_b.dot(theta_final)

In [67]:
print("Com base na taxa de juro nominal, esta é a previsão do preço do ativo:", np.round(y_predict, 2))

Com base na taxa de juro nominal, esta é a previsão do preço do ativo: [[183735.96]]
